# Earl grey theme for Ghostty
## name: earl-grey

palette = 0=#FCFBF9
palette = 1=#A57773
palette = 2=#9DA181 
palette = 3=#AB967A
palette = 4=#7686A9
palette = 5=#A788A2 
palette = 6=#7DA1A1
palette = 7=#7F7A73 
palette = 8=#AEABA6
palette = 9=#8F5652 
palette = 10=#747B4D 
palette = 11=#886A44
palette = 12=#556995  
palette = 13=#83577D  
palette = 14=#477A7B  
palette = 15=#605A52  

background=#FCFBF9
foreground=#605A52
cursor-color=#7686A9
selection-foreground=#605A52
selection-background=#CCB9C7
