#!/usr/bin/env bash

SKETCHYBAR_DIR="$HOME/nix/home/custom/sketchybar"
PLUGIN_DIR="$SKETCHYBAR_DIR/plugins"

# Source colors
source "$SKETCHYBAR_DIR/colors"

MONOSPACE_FONT='JetBrainsMono Nerd Font'
SANS_FONT='SF UI Text'

#
# Bar settings
#
sketchybar --bar height=23 \
  blur_radius=50 \
  position=top \
  padding_left=0 \
  padding_right=0 \
  margin=0 \
  y_offset=0 \
  corner_radius=0 \
  sticky=on \
  color="$SK_BAR"

sketchybar --default updates=when_shown \
  drawing=on \
  icon.font="$MONOSPACE_FONT:Regular:14.0" \
  icon.color="$SK_TEXT" \
  label.font="$SANS_FONT:Regular:14.5" \
	label.padding_left=2 \
  label.padding_right=2 \
  icon.padding_left=3 \
  icon.padding_right=5 \
  background.padding_left=5 \
  background.padding_right=5 \
  background.corner_radius=0 \
  label.color="$SK_TEXT" \
  background.height=34

#
# Item defaults
#

sketchybar --add event aerospace_workspace_change
LABELS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
LEFT_SPACE_ITEMS=()
INDEX=0

for sid in $(aerospace list-workspaces --all); do
  label="${LABELS[$INDEX]:-}"
  item="space.$sid"
  LEFT_SPACE_ITEMS+=("$item")

  sketchybar --add item "$item" left \
    --subscribe "$item" aerospace_workspace_change \
    --set "$item" \
      background.color="$SK_SPACE_HL_BG"\
      background.corner_radius=0 \
      background.height=50\
			background.padding_left=0 \
		  background.padding_right=0 \
			background.width=50 \
      background.drawing=off \
      label="$label" \
      icon.padding_left="0" \
      icon.padding_right="0" \
      label.padding_left="10" \
      label.padding_right="10" \
			label.font="$MONOSPACE_FONT:Regular:14.5" \
      click_script="aerospace workspace $sid" \
      script="$PLUGIN_DIR/aerospace.sh $sid"

  ((INDEX++))
done

#
# Right items
#

#
# Center items
#

## Focused app name
sketchybar --add item front_app left \
  --set front_app script="$PLUGIN_DIR/front_app.sh" \
  icon.padding_left=0 \
  icon.padding_right=4 \
  icon.drawing=off \
  label.font="$MONOSPACE_FONT:Regular:13.0" \
  --subscribe front_app front_app_switched
#
# Right items
#

sketchybar --add item clock right \
  --set clock update_freq=5 \
  background.color="$SK_ITEM_BG" \
  icon.drawing=off\
  icon=" 􀐬 " \
  label.padding_left=2 \
  label.padding_right=12 \
  label.font="$MONOSPACE_FONT:Regular:14.0" \
  script="$PLUGIN_DIR/clock.sh" \
  background.padding_right=0 \
  \
  --add event input_change 'AppleSelectedInputSourcesChangedNotification' \
  --add item keyboard right \
  --set keyboard script="$PLUGIN_DIR/keyboard.sh" \
  label.font="$MONOSPACE_FONT:Regular:14.5" \
  --subscribe keyboard input_change \
  \
  --add item battery right \
  --set battery script="BATTERY_LOW=$SK_BATTERY_LOW BATTERY_CHARGING=$SK_BATTERY_CHARGING $PLUGIN_DIR/battery.sh" \
  label.font="$MONOSPACE_FONT:Regular:14.0" \
  update_freq=30 \
  --subscribe battery system_woke power_source_change \
  \
  --add item cpu right \
  --set cpu update_freq=2 \
  label.font="$MONOSPACE_FONT:Regular:14.0" \
  icon="| 􀧓 "\
  script="$PLUGIN_DIR/cpu.sh"\
  \
  --add item ram right \
  --set ram update_freq=15 \
  label.font="$MONOSPACE_FONT:Regular:14.0" \
  icon="|  "\
  script="$PLUGIN_DIR/ram.sh" \
  \
  --add item disk right \
  --set disk update_freq=50 \
  label.font="$MONOSPACE_FONT:Regular:14.0" \
  icon="| 󰋊 "\
  script="$PLUGIN_DIR/disk.sh" \
  \
  --add item mpd right \
  --set mpd update_freq=2 \
  --set mpd script="$PLUGIN_DIR/mpd.sh" \
  label.font="$MONOSPACE_FONT:Regular:14.0" \
  --set mpd click_script="mpc toggle" \
  \
sketchybar --update
echo "sketchybar configuration loaded.."
